[package]
name = "energy-factory-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["you"]

[dev-dependencies]
[dependencies.energy-factory]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.2"
