[package]
name = "farm_token_merge"
version = "0.0.0"
authors = [ "catalin-neagu <catalin.neagu@elrond.com>",]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies.common_structs]
path = "../../../common_structs"

[dependencies.common_errors]
path = "../../../common_errors"

[dependencies.permissions_module]
path = "../../permissions_module"

[dependencies.token_merge_helper]
path = "../../token_merge_helper"

[dependencies.farm_token]
path = "../farm_token"

[dependencies.elrond-wasm]
version = "=0.37.0"
features = ["esdt-token-payment-legacy-decode",]

[dependencies.elrond-wasm-modules]
version = "=0.37.0"
