[package]
name = "farm-v13-custom-rewards-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.farm-v13-custom-rewards]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.53.2"
default-features = false
