[package]
name = "locked-token-wrapper-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["you"]

[dev-dependencies]
[dependencies.locked-token-wrapper]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.4"
