[package]
name = "pair-hooks-sample-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.pair-hooks-sample]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.46.1"
default-features = false
