[workspace]
members = [
  "dex",
  "dex/elrond_dex_farm",
  "dex/elrond_dex_farm/abi",
  "dex/elrond_dex_pair",
  "dex/elrond_dex_pair/abi",
  "dex/elrond_dex_router",
  "dex/elrond_dex_router/abi",
  "dex/multi_token_farm",
  "dex/multi_token_farm/abi",

  "distribution",
  "distribution/sc-distribution-rs",
  "distribution/sc-distribution-rs/abi",
  "distribution/sc-proxy-dex",
  "distribution/sc-proxy-dex/abi",

  "sc-locked-asset-factory",
  "sc-locked-asset-factory/abi",
]
