[package]
name = "price-discovery-v2-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.price-discovery-v2]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.53.2"
default-features = false
