[package]
edition = "2018"
name = "distribution"
publish = false
version = "0.0.0"

[lib]
path = "src/lib.rs"

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.factory]
path = "../factory"

[dependencies.elrond-wasm]
version = "=0.28.0"

[dev-dependencies.elrond-wasm-debug]
version = "=0.28.0"
