[package]
edition = "2018"
name = "distribution"
publish = false
version = "0.0.0"

[lib]
path = "src/lib.rs"

[features]
wasm-output-mode = [
  "elrond-wasm-node",
  "token_supply/wasm-output-mode",
]

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.token_supply]
path = "../../common/modules/token_supply"

[dependencies.factory]
path = "../factory"

[dependencies.elrond-wasm]
version = "0.21.1"

[dependencies.elrond-wasm-derive]
version = "0.21.1"

[dependencies.elrond-wasm-node]
optional = true
version = "0.21.1"

[dev-dependencies.elrond-wasm-debug]
version = "0.21.1"
