[package]
name = "router-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.router]
path = ".."

[dependencies.elrond-wasm]
version = "0.27.1"

[dependencies.elrond-wasm-debug]
version = "0.27.1"
