[package]
name = "router-abi"
version = "0.0.0"
authors = ["MultiversX <contact@multiversx.com>"]
edition = "2021"
publish = false
[dependencies.router]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.43.2"
