[package]
name = "token-unstake"
version = "0.0.0"
authors = [ "you",]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "=0.37.0"
features = ["esdt-token-payment-legacy-decode",]

[dev-dependencies.elrond-wasm-debug]
version = "=0.37.0"

[dev-dependencies.elrond-wasm-modules]
version = "=0.37.0"

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"

[dependencies.mergeable]
path = "../../common/traits/mergeable"

[dependencies.utils]
path = "../../common/modules/utils"

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.energy-query]
path = "../../energy-integration/common-modules/energy-query"

[dependencies.week-timekeeping]
path = "../../energy-integration/common-modules/week-timekeeping"

[dependencies.energy-factory]
path = "../energy-factory"

[dependencies.simple-lock]
path = "../simple-lock"
