[package]
name = "proxy-dex"
version = "0.0.0"
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[features]
wasm-output-mode = [
  "elrond-wasm-node",
  "token_supply/wasm-output-mode",
  "token_merge/wasm-output-mode",
  "token_send/wasm-output-mode",
]

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.pair]
path = "../../dex/pair"

[dependencies.farm]
path = "../../dex/farm"

[dependencies.factory]
path = "../factory"

[dependencies.token_supply]
path = "../../common/modules/token_supply"

[dependencies.token_merge]
path = "../../common/modules/token_merge"

[dependencies.token_send]
path = "../../common/modules/token_send"

[dependencies.elrond-wasm]
version = "0.21"

[dependencies.elrond-wasm-derive]
version = "0.21"

[dependencies.elrond-wasm-node]
version = "0.21"
optional = true

[dev-dependencies.elrond-wasm-debug]
version = "0.21"
