[package]
name = "metabonding-staking-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["MultiversX <contact@multiversx.com>"]

[dev-dependencies]
[dependencies.metabonding-staking]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.43.2"
