[package]
name = "sc_whitelist_module"
version = "0.0.0"
authors = [ "you" ]
edition = "2018"

[lib]
path = "src/sc_whitelist_module.rs"

[dependencies.common_errors]
path = "../../common_errors"

[dependencies.elrond-wasm]
version = "=0.37.0"
features = ["esdt-token-payment-legacy-decode",]
