[package]
name = "simple-lock"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@elrond.com>" ]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.29"

[dependencies.elrond-wasm-modules]
version = "0.29"

[dev-dependencies.elrond-wasm-debug]
version = "0.29"

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"
