[package]
name = "simple-lock"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@elrond.com>" ]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "=0.36.1"
features = ["esdt-token-payment-legacy-decode",]

[dependencies.elrond-wasm-modules]
version = "=0.36.1"

[dependencies.common_structs]
path = "../../common/common_structs"

[dev-dependencies.elrond-wasm-debug]
version = "=0.36.1"

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"
