[package]
name = "farm_base_impl"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"
[dependencies.config]
path = "../config"

[dependencies.farm_token]
path = "../farm_token"

[dependencies.rewards]
path = "../rewards"

[dependencies.events]
path = "../events"

[dependencies.contexts]
path = "../contexts"

[dependencies.token_send]
path = "../../token_send"

[dependencies.token_merge_helper]
path = "../../token_merge_helper"

[dependencies.pausable]
path = "../../pausable"

[dependencies.permissions_module]
path = "../../permissions_module"

[dependencies.utils]
path = "../../utils"

[dependencies.common_structs]
path = "../../../common_structs"

[dependencies.common_errors]
path = "../../../common_errors"

[dependencies.mergeable]
path = "../../../traits/mergeable"

[dependencies.fixed-supply-token]
path = "../../../traits/fixed-supply-token"

[dependencies.multiversx-sc]
version = "=0.43.2"
features = ["esdt-token-payment-legacy-decode"]

[dependencies.multiversx-sc-modules]
version = "=0.43.2"
[dev-dependencies.multiversx-sc-scenario]
version = "=0.43.2"
