[package]
name = "simple-lock-whitelist"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@elrond.com>" ]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.simple-lock]
path = "../simple-lock"

[dependencies.utils]
path = "../../common/modules/utils"

[dependencies.elrond-wasm]
version = "0.36.0"
features = ["esdt-token-payment-legacy-decode",]

[dependencies.elrond-wasm-modules]
version = "0.36.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.36.0"

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"
