[package]
name = "contexts"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"

[lib]
path = "src/mod.rs"
[dependencies.common_structs]
path = "../../../common_structs"

[dependencies.common_errors]
path = "../../../common_errors"

[dependencies.farm_token]
path = "../farm_token"

[dependencies.rewards]
path = "../rewards"

[dependencies.token_send]
path = "../../token_send"

[dependencies.token_merge_helper]
path = "../../token_merge_helper"

[dependencies.config]
path = "../config"

[dependencies.pausable]
path = "../../pausable"

[dependencies.permissions_module]
path = "../../permissions_module"

[dependencies.multiversx-sc]
version = "=0.43.2"
features = ["esdt-token-payment-legacy-decode"]

[dependencies.multiversx-sc-modules]
version = "=0.43.2"
