[package]
name = "farm-with-locked-rewards-meta"
version = "0.0.0"
authors = ["MultiversX <contact@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.farm-with-locked-rewards]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.47.5"
default-features = false
