[package]
name = "utils"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"
[dependencies.multiversx-sc]
version = "=0.43.2"
features = ["esdt-token-payment-legacy-decode"]

[dependencies.common_structs]
path = "../../common_structs"

[dependencies.fixed-supply-token]
path = "../../traits/fixed-supply-token"

[dependencies.mergeable]
path = "../../traits/mergeable"
