[package]
name = "farm-staking-proxy-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.farm-staking-proxy]
path = ".."

[dependencies.elrond-wasm]
version = "=0.36.1"

[dependencies.elrond-wasm-debug]
version = "=0.36.1"
