[package]
name = "pair-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2021"
publish = false

[dependencies.pair]
path = ".."

[dependencies.elrond-wasm]
version = "=0.37.0"
features = ["esdt-token-payment-legacy-decode",]

[dependencies.elrond-wasm-debug]
version = "=0.37.0"

