[package]
name = "pausable"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@elrond.com>" ]
edition = "2018"

[lib]
path = "src/pausable.rs"

[dependencies.permissions_module]
path = "../permissions_module"

[dependencies.elrond-wasm]
version = "0.34.0"
