[package]
name = "simple-lock-whitelist-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = [ "Dorin Iancu <dorin.iancu@elrond.com>" ]

[dependencies.simple-lock-whitelist]
path = ".."

[dependencies.elrond-wasm]
version = "=0.37.0"

[dependencies.elrond-wasm-debug]
version = "=0.37.0"
