[package]
name = "token_merge"
version = "0.0.0"
authors = [ "catalin-neagu <catalin.neagu@elrond.com>",]
edition = "2018"

[lib]
path = "src/token_merge.rs"

[features]
wasm-output-mode = [ "elrond-wasm-node",]

[dependencies.common_structs]
path = "../../common_structs"

[dependencies.elrond-wasm]
version = "0.20"
features = ["derive"]
path = "../../../../elrond-wasm-rs/elrond-wasm"

[dependencies.elrond-wasm-derive]
version = "0.20"
path = "../../../../elrond-wasm-rs/elrond-wasm-derive"

[dependencies.elrond-wasm-node]
version = "0.20"
optional = true
path = "../../../../elrond-wasm-rs/elrond-wasm-node"
