[package]
name = "sc-locked-asset-factory-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.sc-locked-asset-factory]
path = ".."

[dependencies.elrond-wasm]
version = "0.17"


[dependencies.elrond-wasm-debug]
version = "0.17"

