[package]
name = "events"
version = "0.0.0"
authors = [ "catalin-neagu <catalin.neagu@elrond.com>",]
edition = "2018"

[lib]
path = "src/events.rs"

[dependencies.common_structs]
path = "../../../common_structs"

[dependencies.contexts]
path = "../contexts"

[dependencies.farm_token]
path = "../farm_token"

[dependencies.elrond-wasm]
version = "0.34.0"
