[package]
name = "events"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"

[lib]
path = "src/events.rs"
[dependencies.common_structs]
path = "../../../common_structs"

[dependencies.contexts]
path = "../contexts"

[dependencies.multiversx-sc]
version = "=0.39.4"
features = ["esdt-token-payment-legacy-decode"]
