[package]
name = "token-unstake-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.token-unstake]
path = ".."

[dependencies.elrond-wasm]
version = "=0.37.0"

[dependencies.elrond-wasm-debug]
version = "=0.37.0"
