[package]
name = "token-unstake-abi"
version = "0.0.0"
authors = ["MultiversX <contact@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.token-unstake]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.60.0"
default-features = false
