[package]
name = "distribution-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.distribution]
path = ".."

[dependencies.elrond-wasm]
version = "0.22.6"


[dependencies.elrond-wasm-debug]
version = "0.22.6"
