[package]
name = "permissions_module"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>", "Claudiu-Marcel Bruda <claudiu.bruda@multiversx.com>"]
edition = "2021"

[lib]
path = "src/permissions_module.rs"

[dependencies]
bitflags = "1.3.2"

[dependencies.common_errors]
path = "../../common_errors"

[dependencies.multiversx-sc]
version = "=0.43.2"
features = ["esdt-token-payment-legacy-decode"]
