[package]
name = "proxy-dex-legacy-meta"
version = "0.0.0"
authors = ["you"]
edition = "2018"
publish = false

[dependencies.proxy-dex-legacy]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.53.2"
default-features = false
