[package]
name = "farm_token"
version = "0.0.0"
authors = [ "catalin-neagu <catalin.neagu@elrond.com>",]
edition = "2018"

[lib]
path = "src/farm_token.rs"

[dependencies.common_structs_old]
path = "../../../common_structs_old"

[dependencies.common_errors_old]
path = "../../../common_errors_old"

[dependencies.config]
path = "../config"

[dependencies.token_send]
path = "../../token_send"

[dependencies.elrond-wasm]
version = "0.28.0"
