[package]
name = "proxy_dex"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"
[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.itertools]
version = "0.10.1"
default-features = false

[dependencies.pair]
path = "../../dex/pair"

[dependencies.farm]
path = "../../dex/farm"

[dependencies.farm-with-locked-rewards]
path = "../../dex/farm-with-locked-rewards"

[dependencies.locking_module]
path = "../../common/modules/locking_module"

[dependencies.legacy_token_decode_module]
path = "../../common/modules/legacy_token_decode_module"

[dependencies.token_merge_helper]
path = "../../common/modules/token_merge_helper"

[dependencies.token_send]
path = "../../common/modules/token_send"

[dependencies.utils]
path = "../../common/modules/utils"

[dependencies.mergeable]
path = "../../common/traits/mergeable"

[dependencies.fixed-supply-token]
path = "../../common/traits/fixed-supply-token"

[dependencies.multiversx-sc]
version = "=0.43.2"
features = ["esdt-token-payment-legacy-decode"]

[dependencies.multiversx-sc-modules]
version = "=0.43.2"

[dependencies.energy-factory]
path = "../energy-factory"

[dependencies.energy-query]
path = "../../energy-integration/common-modules/energy-query"

[dependencies.simple-lock]
path = "../simple-lock"

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.43.2"

[dev-dependencies.pausable]
path = "../../common/modules/pausable"

[dev-dependencies.farm_base_impl]
path = "../../common/modules/farm/farm_base_impl"

[dev-dependencies.config]
path = "../../common/modules/farm/config"

[dev-dependencies.farm_token]
path = "../../common/modules/farm/farm_token"

[dev-dependencies.rewards]
path = "../../common/modules/farm/rewards"

[dev-dependencies.sc_whitelist_module]
path = "../../common/modules/sc_whitelist_module"

[dev-dependencies.farm-boosted-yields]
path = "../../energy-integration/farm-boosted-yields"
