[package]
name = "farm-staking-proxy-v13-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["MultiversX <contact@multiversx.com>"]

[dependencies.farm-staking-proxy-v13]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.53.0"
default-features = false
