[package]
name = "pause-all-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["MultiversX <contact@multiversx.com>"]

[dev-dependencies]
[dependencies.pause-all]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.43.2"
