[package]
name = "proxy_dex-meta"
version = "0.0.0"
authors = ["MultiversX <contact@multiversx.com>"]
edition = "2021"
publish = false
[dependencies.proxy_dex]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.43.2"
