[package]
name = "energy-update-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["MultiversX <contact@multiversx.com>"]

[dev-dependencies]
[dependencies.energy-update]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.43.2"
