[package]
name = "token_merge_helper"
version = "0.0.0"
authors = [ "catalin-neagu <catalin.neagu@elrond.com>",]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies.common_errors]
path = "../../common_errors"

[dependencies.elrond-wasm]
version = "0.36.0"
features = ["esdt-token-payment-legacy-decode",]
