[package]
name = "locking_module"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@elrond.com>" ]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.36.0"
features = ["esdt-token-payment-legacy-decode",]

[dependencies.simple-lock]
path = "../../../locked-asset/simple-lock"

[dependencies.energy-factory]
path = "../../../locked-asset/energy-factory"
