[package]
name = "farm-staking"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.config]
path = "../../common/modules/farm/config"

[dependencies.farm_token]
path = "../../common/modules/farm/farm_token"

[dependencies.rewards]
path = "../../common/modules/farm/rewards"

[dependencies.token_send]
path = "../../common/modules/token_send"

[dependencies.token_merge]
path = "../../common/modules/token_merge"

[dependencies.pausable]
path = "../../common/modules/pausable"

[dependencies.admin_whitelist]
path = "../../common/modules/admin_whitelist"

[dependencies.factory]
path = "../../locked-asset/factory"

[dependencies.pair]
path = "../../dex/pair"

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.common_errors]
path = "../../common/common_errors"

[dependencies.elrond-wasm]
version = "0.34.0"

[dependencies.elrond-wasm-modules]
version = "0.34.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.34.0"

[dev-dependencies]
num-bigint = "0.4.2"
