[package]
name = "mergeable"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"
[dependencies.multiversx-sc]
version = "=0.41.0"
features = ["esdt-token-payment-legacy-decode"]
