[package]
name = "price-discovery-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]

[dependencies.price-discovery]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.4"
default-features = false
