[package]
name = "token_send"
version = "0.0.0"
authors = [ "catalin-neagu <catalin.neagu@elrond.com>",]
edition = "2018"

[lib]
path = "src/token_send.rs"

[dependencies.common_structs]
path = "../../common_structs"

[dependencies.common_errors]
path = "../../common_errors"

[dependencies.elrond-wasm]
version = "=0.37.0"
features = ["esdt-token-payment-legacy-decode",]
