[package]
name = "legacy_token_decode_module"
version = "0.0.0"
authors = [ "Sorin Petreasca <sorin.petreasca@elrond.com>" ]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "=0.38.0"
features = ["esdt-token-payment-legacy-decode",]

[dependencies.common_structs]
path = "../../common_structs"

[dependencies.utils]
path = "../utils"
