[package]
name = "farm-v13-locked-rewards-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.farm-v13-locked-rewards]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.53.0"
default-features = false
